include:
  - template: Auto-DevOps.gitlab-ci.yml

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  DOCKER_HOST: tcp://docker.qinzhiqiang.cn:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""
  # Database
  POSTGRES_ENABLED: "false"
  # use custom test
  TEST_DISABLED: "true"

before_script:
  #- cd $CI_PROJECT_DIR
  - export GOPROXY=https://goproxy.io
  - export GIN_MODE=release
  - export CGO_ENABLED=0
  - export GO111MODULE=on

stages:
  - test
  - build
  - deploy  # dummy stage to follow the template guidelines
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

.auto-deploy:
  image: "kinsprite/gitlab-auto-deploy-image:v0.1.0"

build:
  image: "kinsprite/gitlab-auto-build-image:stable"

golang_test:
  stage: test
  image: golang:1.12.9-alpine3.10
  script:
    - go mod vendor
    - go vet -mod=vendor .
    - go test -mod=vendor .
  only:
    - branches
    - tags
