include:
  - template: Auto-DevOps.gitlab-ci.yml

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  DOCKER_HOST: tcp://docker.qinzhiqiang.cn:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""
  # Database
  POSTGRES_ENABLED: "false"


.auto-deploy:
  image: "kinsprite/gitlab-auto-deploy-image:v0.1.0"

build:
  image: "kinsprite/gitlab-auto-build-image:stable"
