include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  POSTGRES_ENABLED: "false"

.auto-deploy:
  image: "registry.qinzhiqiang.cn/custom-auto-deploy-image:v0.1.0"

build:
  image: "registry.qinzhiqiang.cn/custom-auto-build-image:stable"
